version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_rackiq
    restart: always
    ports:
      - "8000:8000"            # Mapea el puerto local al contenedor
    volumes:
      - ./backend:/code        # Monta el código para desarrollo en caliente
    env_file:
      - .env                   # Carga SUPABASE_URL, DATABASE_URL, etc.
    environment:
      - PORT=8000              # Puerto de escucha dentro del contenedor (debe coincidir con el mapeo)